#!/bin/sh

# .desktop applications dir
userApps="$HOME/.nix-profile/share/applications"

# Found from `echo $XDG_DATA_DIRS`
systemApps="/run/current-system/sw/share/applications"

handle() {


    class=$(hyprctl activewindow -j | jq --raw-output .class)
    #awk -F '>>|,' '{print $2".svg"}'

    userAppPath="$userApps/$class.desktop"
    systemAppPath="$systemApps/$class.desktop"

    # If .desktop file exists in user apps
    if test -f "$userAppPath"; then
        # Get icon name from .desktop file
        iconName=$(cat $userAppPath | grep "Icon=*" | awk -F '=' '{print $2}')

    # If .desktop file exists in system apps
    elif test -f "$systemAppPath"; then
        # Get icon name from .desktop file
        iconName=$(cat $systemAppPath | grep "Icon=*" | awk -F '=' '{print $2}')

    # If no .desktop file exists
    else
        iconName="error"
    fi
    
    echo "$iconName.svg"

  #case $1 in
  #  monitoradded*) do_something ;;
  #  focusedmon*) do_something_else ;;
  #esac
  
}

# Initial call
handle

# Listens for Hyprland events and calls handle() on each one
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done