
general {
    lock_cmd = qs-lock
    before_sleep_cmd = loginctl lock-session    # lock before suspend.

    # hyprland
    #after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Power off monitors
listener {
  timeout = 300 # in seconds

  # niri
  on-timeout = niri msg action power-off-monitors

  # hyprland
  #on-timeout = hyprctl dispatch dpms off
  #on-resume = hyprctl dispatch dpms on
}

# sleep using suspend
listener {
  timeout = 600
  on-timeout = systemctl suspend
}

source=~/.config/leaf-de/hypr/idle.conf
