
export default{
    settings: "preferences-system-symbolic",
    refresh: "view-refresh-symbolic",
    cpu: "cpu-symbolic",
    ram: "ram-symbolic",
    storage: "drive-symbolic",
    cpuTemp: "temp-symbolic",
    shutdown: "system-shutdown-symbolic",
    hibernate: "system-hibernate-symbolic",
    suspend: "system-suspend-symbolic",
    restart: "system-restart-symbolic",
    back: "pan-start-symbolic",
    checkmark: "object-select-symbolic",
    screenRecord: "radio-checked-symbolic",
    deleteItem: "edit-delete-symbolic",
    lock: "lock-symbolic",
    invalidWallpaper: "invalid-wallpaper-symbolic",
    close: "window-close-symbolic",
    notification: "notification-symbolic",
    notificationDisabled: "notifications-disabled-symbolic",
}
