pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../" as Root
import "../Services" as Services

import Quickshell.Hyprland

Singleton {
    id: root
    component MonitorType: QtObject {
        property string name
        property int id
    }

    /*
    property string currentId: {
        let id = ""
        for (let m of root.monitors) {
            const mObj = m.lastIpcObject
            //console.log(`ipc obj: ${JSON.stringify(mObj)}`)
            if (mObj === ({})) {
                console.error(`Error: lastIpcObject empty for ${m.name}`)
                return "???"
            }
            id = id + `${mObj.name}&${mObj.make}&${mObj.model}&${mObj.serial}-`
        }
        console.log("Current id updated: " + id)
        return id
    }
    */

    // Array of `hyprctl monitors -j` objects
    // Useful if properties of the HyprlandMonitor.lastIpcObject are needed
    /*
    property var monitorObjs: Hyprland.monitors.values.map(monitor => {
        Hyprland.refreshMonitors() // Is this not updating the prop before we access it?
        //console.log('property set')
        if (monitor.lastIpcObject === undefined) {
            return null
        }
        return monitor.lastIpcObject
    })
    */

    property list<var> visualMonitors: [] // Holds a list to each visual monitor element
    property list<HyprlandMonitor> monitors: Hyprland.monitors.values
 
    // Generate a unique idententifier for the current monitor configuration
    function generateId(): string {
        let id = ""
        Hyprland.refreshMonitors()
        for (let m of monitors) {
            const mObj = m.lastIpcObject // TODO: Is an empty object when method is ran right after monitor event occured
            console.log(`${m.name}: generatingId for: ${JSON.stringify(mObj)}`)
            if (mObj === undefined) {
                console.error("Error: lastIpcObject undefined for {}")
                return "???"
            }
            id = id + `${mObj.name}&${mObj.make}&${mObj.model}&${mObj.serial}-`
        }
        return id
    }
    // Returns a Hyprland monitor config string
    function generateHyprlandConf(): string {
        Hyprland.refreshMonitors() // TODO: optimize to only call once on monitor event
        let conf = ''
        for (const v of visualMonitors) {
            conf += `monitor=${v.monitor.name},preferred,${v.actualX}x${v.actualY},${v.actualScale}\n`
        }
        return conf
    }
    // Loads any saved config for the current monitors and ports
    function loadConfig(): void { 
        const id = generateId()
        console.log(`loading config for id: ${id}`)
        let conf = ""
        // If a saved config exists
        if (monitorMapFile.adapter.configs[id]) {    
            conf = monitorMapFile.adapter.configs[id]
        }
        else {
            console.log("No saved monitor config found")
            conf = "#No saved config found"
        }
        // Set monitor config
        monitorConfFile.setText(`# This file is autogenerated\n` + conf)
    }

    // Apply the config specified in the monitor settings gui
    function applyConf() {
        const conf = generateHyprlandConf()
        const id = generateId()
        console.log(`applying config for id: ${id}, with conf: ${conf}`)
        console.log(`qml: ${JSON.stringify(monitorMapFile.adapter)}`)
        monitorMapFile.adapter.configs[id] = conf
        console.log(`qml: ${JSON.stringify(monitorMapFile.adapter)}`)
        // Write the changes to the file (needed since these properties on the js obj are not tracked)
        monitorMapFile.writeAdapter() // Causes crash randomly
        // Write the new monitor configuration to the hyprland monitor conf
        monitorConfFile.setText(`# This file is autogenerated\n` + conf)
    }

    function enable(){
        console.log('Enabling Monitor service')
    }

    // Workaround
    Timer {
        id: waitToLoadConfig
        interval: 400
        running: false
        onTriggered: loadConfig()
    }

    Connections {
        target: Hyprland
        function onRawEvent(event) {
            //console.log(`hyprland event: ${event.name}`)

            //Hyprland.refreshMonitors()
            switch (event.name) {
                case "monitoradded":
                case "monitoraddedv2":
                case "monitorremoved":
                case "monitorremovedv2":
                    console.log("monitor event occured")
                    console.log(event.data)
                    Hyprland.refreshMonitors()
                    Hyprland.onMonitorsChanged = () => {
                        console.log(`onMonitorsChanged`)
                    }

                    // Load in a saved monitor config after timeout
                    // Needs timeout because lastIpcObject is empty for the new monitor when it tries to generate the id
                    waitToLoadConfig.running = true

                case "openwindow":
                    generateId()
                default:
                    //console.log("some other event")

            }


            /*
            const id = root.generateId() // Calculate the id for the currnet monitor conf
            if (monitorMapFile.adapter[id]) {
                console.log('found config')
            }
            else {
                console.log('missed config')
                //monitorMapJson.adapter[id] = generateHyprlandConf()
            }
            */
        }
    }

    FileView {
        id: monitorMapFile
        path: Root.State.leafPath + "/hypr/monitorMap.json"

        // Block all operations until the file is loaded
        blockLoading: true

        // Reload the file if it changes
        watchChanges: true 
        onFileChanged: reload()

        // If the adapter's contents change, update the file
        onAdapterUpdated: {
            console.log(`adapter updated`)
            writeAdapter()
        }

        onLoadFailed: (err) => {
            console.log(`File ${path} load failed with ${err}`)
        }
        onLoaded: {
            console.log(`File ${path} load ok, text = ${monitorMapFile.text()}`) 
        }

        // Adapter between qml object and json
        // Values set here are the defaults
        // *Note* This does not create the file with the default values.  It instead 
        // will use these values if they cannot be found in the specified file.
        adapter: JsonAdapter {
            // `()` fixes undefined issue when modifying
            property var configs: ({}) // map of id's to conf's
        } 
    }

    FileView {
        id: monitorConfFile
        path: Root.State.leafPath + "/hypr/monitors.conf"
        onLoaded: {
            console.log(`File ${path} load ok, text = ${text()}`) 
        }
    }
}
