# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # This system has been configured using zfs
  # 
  # Disable zfs auto mounting since we're specifying the drives here.  Or remove the fileSystems entries.
  # See wiki.nixos.org/wiki/ZFS for more info.
  systemd.services.zfs-mount.enable = false;

  # Auto import pools on boot 
  boot.zfs.extraPools = [ "main" ];
  
  # Avoid potential issues with disk ids if pool was create via /dev/disk/by-id
  boot.zfs.devNodes = "/dev/disk/by-id";

  services.zfs.autoScrub.enable = true;
  services.zfs.trim.enable = true;
 
  # ZFS filesystems (datasets)
  fileSystems."/" =
    { device = "main/root";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/nix" =
    { device = "main/nix";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/var" =
    { device = "main/var";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/home" =
    { device = "main/home";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  # Boot filesystem
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43D9-B6C6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/e8cb929c-0ad6-4af1-b43f-8e016968a40a";
	randomEncryption = true;  # Encrypted with a random secret on each boot
	}
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
