.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wallust-cs 1  wallust-3.0 wallust-cs
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH NAME
wallust\-cs \- Apply a certain colorscheme
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH SYNOPSIS
\fBwallust\-cs\fR [\fB\-f\fR|\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-format\fR=\fIFORMAT\fR
Specify a custom format. Without this option, wallust will sequentially try to decode it by trying one by one
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
pywal: uses the wal colorscheme format, see <https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes>
.IP \(bu 2
terminal\-sexy: uses <https://terminal.sexy> JSON export
.IP \(bu 2
wallust: cached wallust files
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIFILE\fR>
Path to the file that has a colorscheme

.SH "SEE ALSO"
.BR wallust (5),
.BR wallust-run (1),
.BR wallust-cs (1),
.BR wallust-theme (1),
.BR wallust-themes [1]
.br
.SH "NOTES"
.nr step 1
.IP " \n+[step]." 4
Suggestions for new colorschemes returned by the
.B themes
subcommand should be filled here.
.RS 4
.I https://codeberg.org/explosion-mental/wallust-themes
.RE
.SH "BUGS"
.I https://codeberg.org/explosion-mental/wallust
